- name: jzmq.clone
  git:
    repo: https://github.com/zeromq/jzmq.git
    dest: /opt/jzmq
- name: jzmq.autogen
  command: ./autogen.sh chdir=/opt/jzmq
- name: jzmq.configure
  command: ./configure chdir=/opt/jzmq
- name: jzmq.make
  command: make chdir=/opt/jzmq
- name: jzmq.make_install
  command: make install chdir=/opt/jzmq
- file: path=/opt/jzmq mode=0755 recurse=yes
