- name: jzmq.clone
  git:
    repo: https://github.com/zeromq/jzmq.git
    dest: /opt/jzmq
    version: v2.2.2
- name: jzmq.autogen
  command: ./autogen.sh chdir=/opt/jzmq
- name: jzmq.configure
  command: ./configure chdir=/opt/jzmq
- name: jzmq.make
  command: make chdir=/opt/jzmq
- name: jzmq.make_install
  command: make install chdir=/opt/jzmq
- name: sbt.lib.create
  file: path=/corenlp/scala/lib state=directory
- name: jzmq.jar.symlink
  file:
    src: /usr/local/share/java/zmq.jar
    dest: /corenlp/scala/lib/
    state: link
