- file:
    path: dest: /etc/apt/sources.list.d/dl_bintray_com_sbt_debian.list
    state: touch
    mode: 0644
- name: sbt.add_repo
  lineinfile:
    dest: /etc/apt/sources.list.d/dl_bintray_com_sbt_debian.list
    line: deb http://dl.bintray.com/sbt/debian /
    mode: 0644
- name: packages.update
  apt: update_cache=yes
- name: packages.install
  apt: 'name={{item}} state=present force=yes'
  with_items:
    - wget
    - build-essential
    - pkg-config
    - make
    - libtool
    - autoconf
    - automake
    - git-core
    - default-jre
    - default-jdk
    - scala
    - sbt
    - supervisor
    - python3.4
    - python3.4-dev
    - python-setuptools
    - python-virtualenv
    - python-dev
    - libzmq3-dev

