- name: sbt.add_repo
  command: 'echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list'
- name: packages.update
  apt: update_cache=yes
- name: packages.install
  apt: 'name={{item}} state=present force=yes'
  with_items:
    - wget
    - build-essential
    - pkg-config
    - sudo
    - make
    - libtool
    - autoconf
    - automake
    - python-openssl
    - git-core
    - default-jre
    - default-jdk
    - scala
    - sbt
    - supervisor
    - python3.4
    - python3.4-dev
    - python-setuptools
    - python-virtualenv
    - python-dev
    - libzmq3-dev

