- hosts: localhost
  vars:
    corenlp_version: 2015-01-29
    corenlp_name: 'stanford-corenlp-full-{{corenlp_version}}'

  tasks:
    - include: tasks/packages.yml tags=packages
    - include: tasks/sbt.yml
    - include: tasks/python.yml tags=python
    - include: tasks/app.yml tags=app
    - include: tasks/jzmq.yml tags=jzmq
    - include: tasks/supervisor.yml tags=supervisor

