- hosts: localhost
  vars:
    corenlp_version: 2015-01-29
    corenlp_name: 'stanford-corenlp-full-{{corenlp_version}}'

  tasks:
    # - include: tasks/packages.yml tags=packages
    # - include: tasks/python.yml tags=python
    - name: app.create_user
      user: name=corenlp home=/corenlp
    - name: app.copy_code
      copy: src=files/ dest=/corenlp owner=corenlp
    - include: tasks/jzmq.yml tags=jzmq
    - include: tasks/app.yml tags=jzmq

